force-app/main/default/objects/Account/fields/Total_Salary__c.field-meta.xml
<CustomField>
    <fullName>Total_Salary__c</fullName>
    <label>Total Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>for before and after delete with checkEmployeeStatus and updateLeftEmployee</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup with Employee as child, for salaries</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyDemo.cls
public class MyDemo{

    public static void countTotalSalary(){
        
        List<Account> accWithEmployees = [SELECT Id, Total_Salary__c, Name, (SELECT Id, Salary__c FROM Employees__r) 
                                          FROM Account 
                                          WHERE CreatedDate = THIS_YEAR];
        
        if(!accWithEmployees.isEmpty()){
            for(Account acc: accWithEmployees){
                Decimal TotalSal = 0;
                for(Employee__c emp: acc.Employees__r){
                    
                    TotalSal = TotalSal + emp.salary__c;
                }
                acc.Total_Salary__c = TotalSal;
            }
        }
        if(!accWithEmployees.isEmpty()){
            update accWithEmployees;
        }
    }
    
    public static void updateContactPhone(){
        List<Account> accList = [SELECT Id, Phone FROM Account WHERE CreatedDate = THIS_YEAR AND Phone!=null];
        Map<Id, Account> accIdToAccountMap = new Map<Id, Account>(accList);
        List<Contact> conList = [SELECT Id, Phone, AccountId From Contact
                                 WHERE AccountId IN: accIdToAccountMap.keySet()];
        
        List<Contact> contactToBeUpdated = new List<Contact>();
        if(!conList.isEmpty()){
            for(Contact con : conList){
                if(accIdToAccountMap.containsKey(con.AccountId)){
                    contact conRec = new contact();
                    conRec.Id = con.Id;
                    conRec.Phone = accIdToAccountMap.get(con.AccountId).Phone;
                    contactToBeUpdated.add(conRec);
                }
            }
        }
        if(!contactToBeUpdated.isEmpty()){
            update contactToBeUpdated;
        }
        
        
    }
}